semd/dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('month/<int:q_month>/', views.index, name='index_by_month'),
    path('month/<int:q_month>/year/<int:q_year>/', views.index, name='index_by_month_year'),
    path('upload/', views.upload_csv, name='upload_csv'),
    path('delete_all_semd/', views.delete_all_semd, name='delete_all_semd'),
]

semd/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls', namespace='dashboard')),
]

semd/dashboard/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse


class Semd(models.Model):
    semd_status = {
            0: "Зарегистрирован в РЭМД",
            1: "Отказано в регистрации",
            2: "Отправлен на регистрацию",
            3: "Не отправлен на регистрацию в РЭМД",
            4: "Синхронная ошибка при отправке от внешней ИС в РЭМД",
        }
    month_str = {
        1: "январь",
        2: "февраль",
        3: "март",
        4: "апрель",
        5: "май",
        6: "июнь",
        7: "июль",
        8: "август",
        9: "сентябрь",
        10: "октябрь",
        11: "ноябрь",
        12: "декабрь",
    }
    otd         = models.CharField(max_length=255, verbose_name="Отделение", default='')
    vid_semd    = models.CharField(max_length=255, verbose_name="Вид СЭМДа", default='')
    personal    = models.CharField(max_length=255, verbose_name="Сотрудник", default='')
    lid         = models.CharField(max_length=255, verbose_name="Локальный идентификатор документа", blank=True)
    semd_date   = models.DateField(verbose_name='Дата регистрации', blank=True, null=True)
    status      = models.CharField(max_length=255, verbose_name="Статус передачи", default='')
    month       = models.IntegerField(verbose_name='Месяц', blank=True, null=True)
    year        = models.IntegerField(verbose_name='Год', blank=True, null=True)
    reg_error   = models.CharField(max_length=4000, verbose_name="Ошибка", blank=True)

    class Meta:
        verbose_name = "СЭМД"
        verbose_name_plural = "СЭМДы"

    def __str__(self):
        return self.lid

    def get_absolute_url(self):
        return reverse("semd_detail", kwargs={"pk": self.pk})
    
    def get_all_month(self):
        return self.objects.order_by('month').values_list('month', flat=True).distinct()
    
    def get_all_year(self):
        return self.objects.values_list('year', flat=True).distinct()

    def get_semd_by_status(self, month, year):
        data = {}
        data["all"]                         = len(self.objects.filter(month=month, year=year))
        data["all_last_month"]              = 100 - (len(self.objects.filter(month=month-1, year=year))/len(self.objects.filter(month=month, year=year)))*100 if len(self.objects.filter(month=month, year=year)) != 0 else 0
        data["registered"]                  = len(self.objects.filter(status=self.semd_status[0], month=month, year=year))
        data["registered_last_month"]       = 100 - (len(self.objects.filter(status=self.semd_status[0], month=month-1, year=year))/len(self.objects.filter(status=self.semd_status[0], month=month, year=year)))*100 if len(self.objects.filter(status=self.semd_status[0], month=month, year=year)) != 0 else 0
        data["not_registered"]              = len(self.objects.filter(status=self.semd_status[1], month=month, year=year)) 
        data["not_registered_last_month"]   = 100 - (len(self.objects.filter(status=self.semd_status[1], month=month-1, year=year))/len(self.objects.filter(status=self.semd_status[1], month=month, year=year)))*100 if len(self.objects.filter(status=self.semd_status[1], month=month, year=year)) != 0 else 0
        data["sent"]                        = len(self.objects.filter(status=self.semd_status[2], month=month, year=year))
        data["sent_last_month"]             = 100 - (len(self.objects.filter(status=self.semd_status[2], month=month-1, year=year))/len(self.objects.filter(status=self.semd_status[2], month=month, year=year)))*100 if len(self.objects.filter(status=self.semd_status[2], month=month, year=year)) != 0 else 0
        data["not_sent"]                    = len(self.objects.filter(status=self.semd_status[3], month=month, year=year))
        data["not_sent_last_month"]         = 100 - (len(self.objects.filter(status=self.semd_status[3], month=month-1, year=year))/len(self.objects.filter(status=self.semd_status[3], month=month, year=year)))*100 if len(self.objects.filter(status=self.semd_status[3], month=month, year=year)) != 0 else 0
        data["error"]                       = len(self.objects.filter(status=self.semd_status[4], month=month, year=year))
        data["error_last_month"]            = 100 - (len(self.objects.filter(status=self.semd_status[4], month=month-1, year=year))/len(self.objects.filter(status=self.semd_status[4], month=month, year=year)))*100 if len(self.objects.filter(status=self.semd_status[4], month=month, year=year)) != 0 else 0
        return data

    def get_all_semd(self):
        return self.objects.count()

    def get_list_of_otd(self):
        return self.objects.values_list('otd', flat=True).distinct()
    
    def get_semd_by_otd(self, otd, month, year):
        data = {       
                'all_semd': self.objects.filter(otd=otd, month=month, year=year).count(),
                'registered': self.objects.filter(otd=otd, status=self.semd_status[0], month=month, year=year).count(),
                'not_registered': self.objects.filter(otd=otd, status=self.semd_status[1], month=month, year=year).count(),
                'sent': self.objects.filter(otd=otd, status=self.semd_status[2], month=month, year=year).count(),
                'not_sent': self.objects.filter(otd=otd, status=self.semd_status[3], month=month, year=year).count(),
                'error': self.objects.filter(otd=otd, status=5, month=month, year=year).count(),
                
        }
        return data
    def get_error_semd(self, otd, month, year):
        data = {
                'error_module': self.objects.filter(otd=otd, reg_error__contains='Ошибка модуля', month=month, year=year).count(),
                'error_registration': self.objects.filter(otd=otd, reg_error__contains='Документ с идентификатором', month=month, year=year).count(),
                'error_dul': self.objects.filter(otd=otd,reg_error__in=['не соответствует данным ГИП', 'Указанное значение [Имя пациента]', 'Пол пациента в ЭМД' ], month=month, year=year).count(),
                'error_version': self.objects.filter(otd=otd, reg_error__contains='запрещена регистрация новых версий', month=month, year=year).count(),
                'error_sign': self.objects.filter(otd=otd, reg_error__contains='Несоответствие данных подписанта в запросе и в сертификате', month=month, year=year).count(),
                'error_technical': self.objects.filter(otd=otd, reg_error__contains='Справочник OID', month=month, year=year).count(),
                'error_else': self.objects.filter(otd=otd, reg_error__contains='Справочник OID', month=month, year=year).count(),
                'all_register' : self.objects.filter(otd=otd, status=self.semd_status[0], month=month, year=year).count(),
                'all_items' : self.objects.filter(otd=otd, month=month, year=year).count(),
        }
       
        return data
    

semd/dashboard/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect
from datetime import datetime


from .models import Semd

def index(request, q_month=datetime.now().month, q_year=datetime.now().year):
    try:
        q_month = int(q_month)
        q_year = int(q_year)
        if not (1 <= q_month <= 12):
            raise ValueError
    except (ValueError, TypeError):
        return HttpResponseBadRequest("Некорректные параметры")
    month = Semd.get_all_month(Semd)
    print(month)
    list_month = []
    for i in month:
        list_month.append({i: Semd.month_str[i]})
    year = Semd.get_all_year(Semd)
    status = Semd.get_semd_by_status(Semd, q_month, q_year)
    otd_list = Semd.get_list_of_otd(Semd)
    semd_by_otd = {otd: Semd.get_semd_by_otd(Semd, otd, q_month, q_year) for otd in otd_list}
    error_by_otd = {otd: Semd.get_error_semd(Semd, otd, q_month, q_year) for otd in otd_list}
    
    data = {
        "status": status,
        #"data": semd_by_otd,
        "error": error_by_otd,
        "month": list_month,
        "year": year,
        "current_month": q_month,
        "current_year": q_year
    }
    return render(request, "dashboard/index.html", context=data)

def delete_all_semd(request):
    print("delete_all_semd")
    if request.method == 'GET':
        Semd.objects.all().delete()
        messages.success(request, "Все записи успешно удалены")
        return redirect('dashboard:upload_csv')  # или другая страница
    return redirect('dashboard:upload_csv')

def upload_csv(request):
    data = {}
    if "GET" == request.method:
        return render(request, "dashboard/upload.html", data)
    
    try:
        csv_file = request.FILES["csv_file"]
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'Файл не является CSV')
            return HttpResponseRedirect(reverse("dashboard:upload_csv"))
        
        # Проверка размера файла
        if csv_file.multiple_chunks():
            messages.error(request, "Файл слишком большой. Максимальный размер: 10 МБ.")
            return HttpResponseRedirect(reverse("dashboard:upload_csv"))
        
        # Читаем файл для подсчета строк
        csv_file.seek(0)  # Возвращаем курсор в начало файла
        total_lines = len(csv_file.read().decode("windows-1251").split("\n"))
        processed = 0
        
        # Возвращаем курсор в начало файла
        csv_file.seek(0)
        file_data = csv_file.read().decode("windows-1251")
        lines = file_data.split("\n")
        
        # Обработка строк
        for line in lines:
            fields = line.split(";")
            if fields[0] != '№' and len(fields) == 19:
                is_present = Semd.objects.filter(lid=fields[11]).exists()
                if not is_present:
                    try:
                        if fields[13] == '':
                            correct_format = None
                        else:
                            date_object = datetime.strptime(fields[13], '%d.%m.%Y')
                            correct_format = date_object.date().isoformat() 
                            month_number = date_object.month
                            year_number = date_object.year
                        semd = Semd(
                            otd=fields[2],
                            vid_semd=fields[4],
                            personal=fields[9],
                            lid=fields[11],
                            status=fields[16],
                            reg_error=fields[18],
                            semd_date=correct_format,
                            month=month_number,
                            year=year_number,
                        )
                        print(semd)
                        semd.save()
                        # Обновляем прогресс
                        processed += 1
                        
                    except Exception as e:
                        messages.error(request, "Невозможно загрузить файл. " + repr(e))
                        pass
                else:
                    print('Запись', fields[11], 'с номером уже существует!') 
                # Обновляем страницу с прогрессом
        messages.info(request, f"Обработано записей: {processed}")
        return render(request, "dashboard/upload.html", {
            "processed": processed
        })
                
    except Exception as e:
        messages.error(request, "Невозможно загрузить файл. " + repr(e))
    return HttpResponseRedirect(reverse("dashboard:upload_csv"))

semd/dashboard/templates/dashboard/index — копия.html
<!DOCTYPE html>
<html lang="en">
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.min.css" />
    <link rel="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css" />
     
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.1/Chart.min.js"></script>
     
    <style>
        * { 
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            text-align: center;
            background-color: #F5F5F5;
            width: 1024px;
            margin: 0 auto;
        }
     
        h2 {
            text-align: center;
            font-family: "Verdana", sans-serif;
            font-size: 40px;
        }
        .nav {

        }
        .dashboard {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            width: 1000px;
        }
        .title {
            margin-top: 50px;
        }
        .el1 {
            margin: auto;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            width: 500px;
            height: 500px;
        }
        .el2 {
            width: 500px;
            height: 500px;
            background-color: green;
        }
        .el3 {
            width: 500px;
            height: 500px;
            background-color: darkred;
        }
        .el4 {
            width: 500px;
            height: 500px;
            background-color: burlywood;
        }
        .canvas {
            margin: auto;
        }

    </style>
     
    <body>
        <div class="nav">
                <h2>Аналитика по ЛПУ</h2>
        </div>
        <container class="dashboard">
            <div class="el1">
                <h1 class="title">По статусу документов</h1>
                <canvas class="canvas" id="myChart"></canvas>
            </div>
            <div class="el2"></div>
            <div class="el3">
                <table>
                    <thead>
                        <tr>
                            <th>Отделение</th>
                            <th>Всего SEMD</th>
                            <th>Зарегистрировано</th>
                            <th>Не зарегистрировано</th>
                            <th>Отправлено</th>
                            <th>Не отправлено</th>
                            <th>Ошибка</th>
                            <th>% Зарегистрировано</th>
                            <th>% Не зарегистрировано</th>
                            <th>% Отправлено</th>
                            <th>% Не отправлено</th>
                            <th>% Ошибка</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for otd_name, stats in data.items %}
                            <tr>
                                <td>{{ otd_name }}</td>
                                <td>{{ stats.all_semd }}</td>
                                <td>{{ stats.registered }}</td>
                                <td>{{ stats.not_registered }}</td>
                                <td>{{ stats.sent }}</td>
                                <td>{{ stats.not_sent }}</td>
                                <td>{{ stats.error }}</td>
                                <td>{{ stats.percent_registered }}%</td>
                                <td>{{ stats.percent_not_registered }}%</td>
                                <td>{{ stats.percent_sent }}%</td>
                                <td>{{ stats.percent_not_sent }}%</td>
                                <td>{{ stats.percent_error }}%</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="el4"></div>
            
        </container>
     
    <script type="text/javascript">

        $(function () {
            var data = [
            {
                value: {{status.1}},
                color:"#F7464A",
                highlight: "#F7464A",
                label: "Ошибка регистрации в РЭМД"
            },
            {
                value: {{status.0}},
                color: "#32CD32",
                highlight: "#32CD32",
                label: "Зарегистрирован в РЭМД"
            },
            {
                value: {{status.2}},
                color: "#FFD700",
                highlight: "#FFD700",
                label: "Отправлен на регистрацию в РЭМД"
            },
            {
                value: {{status.3}},
                color: "#FF8C00",
                highlight: "#FF8C00",
                label: "Подписан. Не отправлен на регистрацию в РЭМД"
            },
            {
                value: {{status.4}},
                color: "#696969",
                highlight: "#696969",
                label: "Системные ошибки"
            }
        ]
            var option = {
            responsive: true,
            };
            // Get the context of the canvas element we want to select
            var ctx = document.getElementById("myChart").getContext('2d');
            var myPieChart = new Chart(ctx).Pie(data,option); //'Line' defines type of the chart.
        });
    </script>
    </body>
</html>

semd/dashboard/templates/dashboard/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <title>This is a Title</title>
    
</head>
<body>

	<div class="container">
		<div class="navbar">
			<div class="navbar__title">
				<h4 style="color: var(--primary-color);">Аналитика <span style="color: var(--primary-green);">360</span></h4>
			</div>
			<div class="navbar__body">
				<ul class="navbar__body-list">
					<li>
						<a href="">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" style="fill: var(--text-color);"><path d="M3 13h1v7c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2v-7h1a1 1 0 0 0 .707-1.707l-9-9a.999.999 0 0 0-1.414 0l-9 9A1 1 0 0 0 3 13zm7 7v-5h4v5h-4zm2-15.586 6 6V15l.001 5H16v-5c0-1.103-.897-2-2-2h-4c-1.103 0-2 .897-2 2v5H6v-9.586l6-6z"></path></svg>
							<span class="navbar__body-list-span">Общая</span>
						</a>
					</li>
					<li>
						<a href="">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" style="fill: var(--text-color);"><path d="M15 2.013H9V9H2v6h7v6.987h6V15h7V9h-7z"></path></svg>
							<span  class="navbar__body-list-span">По отделениям</span>
						</a>
					</li>
					<li>
						<a href="">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" style="fill: var(--text-color);"><circle cx="12" cy="4" r="2"></circle><path d="M12 18h2v-5h2V9c0-1.103-.897-2-2-2h-4c-1.103 0-2 .897-2 2v4h2v5h2z"></path><path d="m18.446 11.386-.893 1.789C19.108 13.95 20 14.98 20 16c0 1.892-3.285 4-8 4s-8-2.108-8-4c0-1.02.892-2.05 2.446-2.825l-.893-1.789C3.295 12.512 2 14.193 2 16c0 3.364 4.393 6 10 6s10-2.636 10-6c0-1.807-1.295-3.488-3.554-4.614z"></path></svg>
							<span class="navbar__body-list-span">По врачам</span>
						</a>
					</li>
					<li>
						<a href="">
							<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" style="fill: var(--text-color);"><path d="M3 13h1v7c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2v-7h1a1 1 0 0 0 .707-1.707l-9-9a.999.999 0 0 0-1.414 0l-9 9A1 1 0 0 0 3 13zm7 7v-5h4v5h-4zm2-15.586 6 6V15l.001 5H16v-5c0-1.103-.897-2-2-2h-4c-1.103 0-2 .897-2 2v5H6v-9.586l6-6z"></path></svg>
							<span class="navbar__body-list-span">По типу СЭМД</span>
						</a>
					</li>
				</ul>
			</div>
    		
	    </div>
	    <div class="body">
	    	<div class="body__head month-selector">
                {% for m in month %}
                    {% for key, value in m.items %}
                    <div class="body__head-month">
                        <a href="{% url 'dashboard:index_by_month' key %}" class="body__head-month-link month-link {% if key == current_month %}active{% endif %}">
                            <span >{{ value|default:'Нет данных' }}</span>
                        </a>
                    </div>
                    {% endfor %}
                {% endfor %}
            </div>
	    	<div class="body__container">
	    		<div class="body__container-box">
	    			<div class="body__container-box-element">
	    				<div class="body__container-box-element-head">
	    					<span class="body__container-box-element-value">{{status.all}}</span>
	    					<span class="body__container-box-element-value-percent">{{status.all_last_month}}%</span>
	    				</div>
	    				<span class="body__container-box-element-title">Всего</span>
	    			</div>
	    			<div class="body__container-box-element">
	    				<div class="body__container-box-element-head">
	    					<span class="body__container-box-element-value">{{status.registered}}</span>
	    					<span class="body__container-box-element-value-percent">{{status.registered_last_month}}%</span>
	    				</div>
	    				<span class="body__container-box-element-title">Зарегистрировано</span>
	    			</div>
	    			<div class="body__container-box-element">
	    				<div class="body__container-box-element-head">
	    					<span class="body__container-box-element-value">{{status.not_registered}}</span>
	    					<span class="body__container-box-element-value-percent">{{status.not_registered_last_month}}%</span>
	    				</div>
	    				<span class="body__container-box-element-title">Ошибок</span>
	    				
	    			</div>
	    			<div class="body__container-box-element">
	    				<div class="body__container-box-element-head">
	    					<span class="body__container-box-element-value">{{status.sent}}</span>
	    					<span class="body__container-box-element-value-percent">{{status.sent_last_month}}%</span>
	    				</div>
	    				<span class="body__container-box-element-title">На регистрации</span>
	    				
	    			</div>
	    			<div class="body__container-box-element">
	    				<div class="body__container-box-element-head">
	    					<span class="body__container-box-element-value">{{status.not_sent}}</span>
	    					<span class="body__container-box-element-value-percent">{{status.not_sent_last_month}}%</span>
	    				</div>
	    				<span class="body__container-box-element-title">Не отправленых</span>
	    				
	    			</div>
	    			<div class="body__container-box-element">
	    				<div class="body__container-box-element-head">
	    					<span class="body__container-box-element-value">{{status.error}}</span>
	    					<span class="body__container-box-element-value-percent">{{status.error_last_month}}%</span>
	    				</div>
	    				<span class="body__container-box-element-title">Системные ошибки</span>
	    				
	    			</div>
	    		</div>
	    		<!--<div class="body__container-box-top-diagrams">
	    			<div class="body__container-box-top-diagrams-element">1</div>
	    			<div class="body__container-box-top-diagrams-element">1</div>
	    			<div class="body__container-box-top-diagrams-element">1</div>
	    		</div>-->
	    		<div class="body__container-box-center">
	    			<table>
						<thead>
						  <tr>
							<td>Отделение</td>
							<td>Зарегистрировано</td>
							<td>Ошибка модуля отправки</td>
							<td>Повторная регистрации</td>
							<td>ДУЛ не соответствует</td>
							<td>Запрещена регистрация новой версии</td>
							<td>Не соответствуют данные подписанта</td>
							<td>Технические ошибки</td>
							<td>Прочие ошибки</td>
							<td>Всего документов</td>
						  </tr>
						</thead>
						<tbody>
                            {% for otd_name, errors in error.items %}
						  <tr>
							<td>{{otd_name}}</p></td>
							<td><p>{{errors.all_register}}</p></td>
							<td><p>{{errors.error_module}}</p></td>
							<td><p>{{errors.error_registration}}</p></td>
							<td><p>{{errors.error_dul}}</p></td>
							<td><p>{{errors.error_version}}</p></td>
							<td><p>{{errors.error_sign}}</p></td>
							<td><p>{{errors.error_technical}}</p></td>
							<td><p>{{errors.error_else}}</p></td>
							<td><p>{{errors.all_items}}</p></td>
						  </tr>
                            {% endfor %}
						</tbody>
					  </table>
	    		</div>
	    		
	    	</div>
	    </div>	
	</div>
	

</body>
<footer>

</footer>

</html>

semd/dashboard/templates/dashboard/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .progress-container {
            margin-bottom: 20px;
        }
        
        .progress-bar {
            transition: width 0.5s ease-in-out;
        }
        
        .progress-text {
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Загрузка CSV файла</h2>
        <form action="{% url 'dashboard:upload_csv' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            <div class="form-group">
                <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
                <div class="col-md-8">
                    <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                    <button class="btn btn-primary"> 
                        <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>
                        Upload
                    </button>
                </div>
            </div>
            
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            
            {% if progress %}
                <div class="progress">
                    <div class="progress-bar progress-bar-striped active" role="progressbar"
                        aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100"
                        style="width: {{ progress }}%;">
                        {{ progress }}%
                    </div>
                </div>
                <p>
                    Обработано: {{ processed }} из {{ total }} записей
                </p>
            {% endif %}
        </form>
        <form method="post" action="{% url 'dashboard:delete_all_semd' %}" style="margin-top:20px;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите удалить все записи?')">
                <span class="glyphicon glyphicon-trash"></span> Удалить все записи Semd
            </button>
        </form>
        <a href="{% url 'dashboard:index' %}" class="btn btn-primary" style="margin-top:20px;">
            <span class="glyphicon glyphicon-arrow-left"></span> Back
        </a>
    </div>
</body>
</html>